/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pl.jac.mija.gson

class App {
    val greeting: String
        get() {
            return "Hello world."
        }

    fun wiocha(): Boolean {
        val x = if (true) "aa" else "bb";

        if (true) {

        } else if (false) {

        }
        return true;
    }
}

fun main(args: Array<String>) {
    println(App().greeting)
}
